### ISSUE TITLE
Doesn't work 👎 

### ISSUE THREAD

**Issue by stesteau** [livepeer/livepeer-python#1]
Hello,

Not sure what is up with the API but it doesn't work. I can't install it from pip. When I clone the repo, I had to remove typos such as

`from .export_task_params import ExportTaskParams, ExportTaskParams1`
`class CreatorID1:`

Inexistant file import: `from .input_creator_id import InputCreatorID`

🤷

**Comment by suhailkakar** [comment]
Hi @stesteau 

Can you elaborate more about what problem you are facing or any specific errors?

> I just tried now and was able to interact with SDK

**Comment by DappaDanDev** [comment]
I can also report this not working unfortunately. Cant import it after the pip install, tried multiple ways with no luck.

**Comment by suhailkakar** [comment]
Taking a look right now @DappaDanDev - thanks for reporting!

**Comment by suhailkakar** [comment]
hey there! we've just released a new version of python sdk (0.0.2) which fixes this issue.
 
i'm going to close this issue, but feel free to open a new one if you till have any issues with sdk.
